import dotenv from 'dotenv';

dotenv.config({ override: true });

const {
  MONGODB_URI,
  MONGODB_VERCEL_URI,
  NODE_ENV,
  PORT,
  CORS_ALLOWED_DOMAINS,
  SWAGGER_DOMAINS,
  SWAGGER_CSS_URL,
  JWT_SECRET,
  JWT_LIFETIME,
  REDIS_HOST,
  CLOUDINARY_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  SENDGRID_API_KEY,
  SENDGRID_USER_VERIFICATION_TEMPLATE_ID,
  SENDGRID_USER_VERIFICATION_URL,
  SENDGRID_PASSWORD_RESET_URL,
  SENDGRID_PASSWORD_RESET_TEMPLATE_ID
} = process.env;

export default {
  MONGODB_URI,
  MONGODB_VERCEL_URI,
  NODE_ENV,
  PORT,
  CORS_ALLOWED_DOMAINS,
  SWAGGER_DOMAINS,
  SWAGGER_CSS_URL,
  JWT_SECRET,
  JWT_LIFETIME,
  REDIS_HOST,
  CLOUDINARY_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  SENDGRID_API_KEY,
  SENDGRID_USER_VERIFICATION_TEMPLATE_ID,
  SENDGRID_USER_VERIFICATION_URL,
  SENDGRID_PASSWORD_RESET_URL,
  SENDGRID_PASSWORD_RESET_TEMPLATE_ID
};
